### ISSUE TITLE
Raise UnicodeDecodeError in runtime

### ISSUE THREAD

**Issue by Too-Naive** [Too-Naive/Things-Forward-telegram#2]
Error message detail:
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 2: invalid start byte
```

**Comment by Too-Naive** [comment]
Traceback:
```
'utf-8' codec can't decode byte 0xbb in position 2: invalid start byte
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pyrogram/client/dispatcher/dispatcher.py", line 156, in update_worker
    chats
  File "/usr/lib/python3.7/site-packages/pyrogram/client/ext/utils.py", line 562, in parse_messages
    reply_markup = pyrogram_types.InlineKeyboardMarkup.read(reply_markup)
  File "/usr/lib/python3.7/site-packages/pyrogram/client/types/bots/inline_keyboard_markup.py", line 46, in read
    row.append(InlineKeyboardButton.read(j))
  File "/usr/lib/python3.7/site-packages/pyrogram/client/types/bots/inline_keyboard_button.py", line 94, in read
    callback_data=b.data.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 2: invalid start byte
```

**Comment by Too-Naive** [comment]
The error is generated by pyrogram library, so I add `wontfix` label in this issue.

**Comment by Too-Naive** [comment]
I think i found a way to fix this issue, use patch for `pyrogram.client.types.bots.InlineKeyboardButton`, add a parameter `errors='ignore'` when calling `.decode()`.

**Comment by Too-Naive** [comment]
And it works for me now.
